# Generated by Django 3.0.5 on 2020-09-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200903_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
