# Generated by Django 3.0.5 on 2020-09-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_book_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book',
        ),
        migrations.DeleteModel(
            name='person',
        ),
    ]
